FROM node:21.6.2-slim as ReactHashApp

# Copy package.json
RUN mkdir -p /var/www/sem_project/
COPY ./ /var/www/sem_project/

WORKDIR /var/www/sem_project/

RUN npm install
RUN npm run build


FROM php:8.2-apache

RUN apt-get update
RUN apt-get install -y curl wget build-essential autoconf automake cmake


# Copy project directory
RUN mkdir -p /var/www/sem_project
COPY ./* /var/www/sem_project

# Copy built React applications
COPY --from=ReactHashApp /var/www/sem_project/public /var/www/sem_project/public

USER root

# Install Wireshark 4.2.4
WORKDIR /tmp/wireshark
RUN apt-get install -y libspeexdsp-dev systemd flex qt6-* libgtk-3-dev libpcap-dev libgcrypt20-dev \
    libgpg-error-dev qttools5-dev qttools5-dev-tools libqt5svg5-dev libtool libc-ares2 libc-ares-dev \

RUN wget https://www.wireshark.org/download/src/all-versions/wireshark-4.2.4.tar.xz
RUN tar -xf wireshark-4.2.4.tar.xz

WORKDIR /tmp/wireshark/wireshark-4.2.4/

RUN mkdir build

WORKDIR /tmp/wireshark/wireshark-4.2.4/build

RUN groupadd -g 62 wireshark
RUN cmake ..
RUN make
RUN make install

# install Python3.11.2
RUN mkdir -p /tmp/pythonInstallation
WORKDIR /tmp/pythonInstallation
RUN apt-get install -y libncursesw5-dev libssl-dev \
     libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev
RUN wget https://www.python.org/ftp/python/3.11.2/Python-3.11.2.tgz
RUN tar -xzf Python-3.11.2.tgz
WORKDIR /tmp/pythonInstallation/Python-3.11.2
RUN ./configure --enable-optimizations
RUN make -j 4
RUN make altinstall

# check python version
RUN python3.11 -V

# Install python dependencies:
# Python dependencies:
RUN apt-get install -y dbus libdbus-1-3 libdbus-1-dev
COPY ./installationFiles/requirements.txt /tmp/requirements.txt
RUN pip3.11 install -r /tmp/requirements.txt


# check version
RUN wireshark -v

# Install aria2c, redis, supervisor
RUN apt-get install -y aria2 redis supervisor

WORKDIR /var/www/

# Configure Laravel
RUN a2enmod rewrite

RUN docker-php-ext-install pdo_mysql zip

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install dependencies
RUN composer install

# Setup mariaDB
FROM mariadb:latest
# Config database data
ENV MYSQL_DATABASE=sem_project
ENV MYSQL_ROOT_PASSWORD=root
EXPOSE 3306

WORKDIR /var/www/sem_project

# run laravel server
CMD php artisan serve --host=0.0.0.0 --port=8080
EXPOSE 8080

# Create sotrage simlink
CMD php artisan storage:link

# migrate database
CMD php artisan migrate

# seed data to database
CMD php artisan db:seed --class=UserSeeder
CMD php artisan db:seed --class=EmulatorSeeder

# Configure supervisor
COPY ./installationFiles/laravel_workers_queue.conf /etc/supervisor/conf.d/laravel_workers_queue.conf

RUN supervisorctl reread && supervisorctl update && supervisorctl start laravel_workers_queue.conf

# .env laravelu

