FROM php:8.2-apache

USER root

RUN apt-get update
RUN apt-get install -y curl wget build-essential autoconf automake cmake sudo aria2 redis libzip-dev

# install Python3.11.2
RUN mkdir -p /tmp/pythonInstallation
WORKDIR /tmp/pythonInstallation
RUN apt-get install -y libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev
RUN wget https://www.python.org/ftp/python/3.11.2/Python-3.11.2.tgz
RUN tar -xzf Python-3.11.2.tgz
WORKDIR /tmp/pythonInstallation/Python-3.11.2
RUN ./configure --enable-optimizations
RUN make -j 4
RUN make altinstall

# check python version
RUN python3.11 -V

# Install python dependencies:
RUN apt-get install -y dbus libdbus-1-3 libdbus-1-dev libcairo2-dev libgirepository1.0-dev
COPY ./installationFiles/requirements.txt /tmp/requirements.txt
RUN pip3.11 install -r /tmp/requirements.txt

# Install Wireshark 4.2.4
WORKDIR /tmp/wireshark
RUN apt-get install -y libspeexdsp-dev systemd flex qt6-* libgtk-3-dev libpcap-dev libgcrypt20-dev libgpg-error-dev qttools5-dev qttools5-dev-tools libqt5svg5-dev libtool libc-ares2 libc-ares-dev

RUN wget https://www.wireshark.org/download/src/all-versions/wireshark-4.2.4.tar.xz
RUN tar -xf wireshark-4.2.4.tar.xz

WORKDIR /tmp/wireshark/wireshark-4.2.4/

RUN mkdir build

WORKDIR /tmp/wireshark/wireshark-4.2.4/build

RUN cmake ..
RUN make
RUN make install

# check version
RUN wireshark -v

# Setup wireshark for none root users
RUN groupadd wireshark
RUN usermod -a -G wireshark www-data

# change permissions for dumpcap
RUN chgrp wireshark /usr/local/bin/dumpcap
RUN chmod 4750 /usr/local/bin/dumpcap
