##
# @file Dockerfile_hashapp
# @author Kristián Kičinka (xkicin02)
#
# @copyright Copyright (c) 2024
#

FROM node:21.6.2-slim as ReactHashApp

USER root
# Copy package.json
RUN mkdir -p /var/www/sem_project/
RUN chown -R www-data:www-data /var/www/

# Copy React data
USER www-data
COPY package.json /var/www/sem_project/
COPY package-lock.json /var/www/sem_project/
COPY resources /var/www/sem_project/resources
COPY public /var/www/sem_project/public
COPY scripts /var/www/sem_project/scripts
COPY vite.config.mjs /var/www/sem_project/

# Change directory ownership
USER root
RUN chown -R www-data:www-data /var/www/sem_project/

USER www-data
WORKDIR /var/www/sem_project/

# Build frontend
RUN npm install
RUN npm run build

#############
# WEB IMAGE #
#############
FROM sem_python_wireshark_php8.3:latest
USER root

# Set max file and post size limits
COPY installationFiles/custom_php_settings.ini /usr/local/etc/php/conf.d/custom_php_settings.ini

# Install needed dependencies
RUN apt-get update
RUN apt-get install -y curl wget build-essential autoconf automake cmake sudo aria2 libzip-dev

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Configure Laravel
RUN a2enmod rewrite

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql zip

# Add apache2 to public direcotry
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# Set custom port to web server
ENV APACHE_HTTP_PORT=8081
RUN sed -i "s/Listen 80/Listen $APACHE_HTTP_PORT/" /etc/apache2/ports.conf
RUN sed -i "s/<VirtualHost \*:80>/<VirtualHost *:$APACHE_HTTP_PORT>/" /etc/apache2/sites-available/000-default.conf

##########
# Docker #
##########

ARG DOCKER_GROUP_ID

# Create docker installation file
RUN cat > /mnt/docker_install.sh <<EOF
# Add Docker's official GPG key:
    apt-get update
    apt-get install -y ca-certificates curl
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc

    # Add the repository to Apt sources:
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update

    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    usermod -aG docker www-data
EOF

# Docker installation
RUN sh /mnt/docker_install.sh

# Changing docker group gid to gid of docker group in host system
# RUN groupmod -g $DOCKER_GROUP_ID docker

USER www-data
# Copy project directory
RUN mkdir -p /var/www/html
COPY . /var/www/html

WORKDIR /var/www/html
USER root

# Set permissions
RUN chown -R www-data:www-data /var/www/
RUN chmod -R 0776 /var/www/html/storage /var/www/html/bootstrap/cache

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
USER www-data

# Install composer dependencies
RUN composer install

# Copy built React applications
COPY --from=reacthashapp /var/www/sem_project/public /var/www/html/public

USER root
# Install networking and database tools
RUN apt update
RUN apt install -y vim iproute2 net-tools iputils-ping mariadb-client

WORKDIR /var/www/html

# Create sotrage simlink
USER www-data
RUN php artisan storage:link

#Create file structure
RUN mkdir -p storage/app/public/pcaps
RUN mkdir -p storage/app/public/uploads/apk_inserted
RUN mkdir -p storage/app/public/uploads/apk_downloaded
RUN mkdir -p storage/app/public/uploads/text_inserted
RUN mkdir -p storage/app/public/uploads/pcap_inserted

# Create log files
RUN mkdir -p storage/logs
RUN touch storage/logs/default_worker.log
USER root

# Install supervisor
RUN apt update
RUN apt install -y supervisor
COPY installationFiles/laravel_workers_queue.conf /etc/supervisor/conf.d/laravel_workers_queue.conf

USER root
# Change folders permissions
RUN chown -R www-data:www-data /var/www/html/storage/app/public/*
RUN chmod -R 0776 /var/www/html/storage/app/public/*

############
#ENTRYPOINT#
############
# Start supervisor and apache in etntrypoint
RUN cat > /mnt/entrypoint.sh <<EOF
chown root:docker /var/run/docker.sock
chown -R www-data:www-data /var/www/html/storage/app/public/*
service supervisor start
apache2-foreground
EOF

USER root
ENTRYPOINT ["/bin/bash", "/mnt/entrypoint.sh"]
