##
# @file docker-compose.yml
# @author Kristián Kičinka (xkicin02)
#
# @copyright Copyright (c) 2024
#

version: '3.8'

services:
    # Main app container
    web:
        image: sem_hashapp:latest
        container_name: hashapp_web
        privileged: true
        env_file:
            - ../.env
        network_mode: host
        depends_on:
            - db
        volumes:
            -   /var/run/docker.sock:/var/run/docker.sock
            -   shared_dir:/var/www/html/storage

    # Database container
    db:
        image: mariadb
        container_name: hashapp_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sem_project
            MYSQL_USER: sem_project
            MYSQL_PASSWORD: password
        network_mode: host

    # Redis
    redis:
        image: redis:bookworm
        container_name: hashapp_redis
        command: redis-server --save 20 1 --loglevel warning
        network_mode: host

    # Android emulator container 01
    emulator_01:
        image: sem_emulator_vm:latest
        container_name: emulator_01
        privileged: true
        deploy:
            resources:
                limits:
                    cpus: "4.0"
                    memory: 4g
        networks:
            - em_net_01
        volumes:
            - shared_dir:/mnt/storage
        depends_on:
            - web

    # Android emulator container 02
    emulator_02:
        image: sem_emulator_vm:latest
        container_name: emulator_02
        privileged: true
        deploy:
            resources:
                limits:
                    cpus: "4.0"
                    memory: 4g
        networks:
            - em_net_02
        volumes:
            - shared_dir:/mnt/storage
        depends_on:
            - web

# Network adapter for emulator 02
networks:
    # Network adapter for emulator 01
    em_net_01:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.name: br-em-01

    # Network adapter for emulator 02
    em_net_02:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.name: br-em-02

# Shared directory for APK files
volumes:
    shared_dir:
        driver: local
