##
# @file Dockerfile_emulators
# @author Kristián Kičinka (xkicin02)
# @copyright 2024
##

FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
  openjdk-17-jdk curl wget unzip zip bzip2 ca-certificates \
  libdrm-dev libxkbcommon-dev libgbm-dev libasound-dev libnss3 \
  libxcursor1 libpulse-dev libxshmfence-dev xauth xvfb git x11vnc \
  fluxbox wmctrl libdbus-glib-1-2 aapt && \
  rm -rf /var/lib/apt/lists/*

# Cesty a premenné prostredia
ENV ANDROID_SDK_ROOT=/opt/android-sdk
ENV ANDROID_HOME=/opt/android-sdk
ENV PATH=$PATH:/opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/emulator:/opt/android-sdk/platform-tools

# Stiahnutie a inštalácia Android Command Line Tools (do "latest")
WORKDIR /tmp/android_emulator
RUN curl -fsSL -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip && \
    mkdir -p ${ANDROID_SDK_ROOT}/cmdline-tools && \
    unzip -q cmdline-tools.zip -d /tmp/android_emulator && \
    mkdir -p ${ANDROID_SDK_ROOT}/cmdline-tools/latest && \
    mv cmdline-tools/* ${ANDROID_SDK_ROOT}/cmdline-tools/latest/ && \
    rm -rf /tmp/android_emulator/*

# Akceptácia licencií
RUN yes | sdkmanager --licenses

# Základné balíky
RUN sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platform-tools" "emulator"

# Platformy a imagy
RUN sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platforms;android-30" \
    "system-images;android-30;google_apis;x86_64"

# Build-tools (toto predtým padalo)
RUN sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "build-tools;30.0.3"

# Vytvorenie AVD
RUN echo no | avdmanager create avd --force \
  -n android-30-x86_64 \
  -k "system-images;android-30;google_apis;x86_64"

# Štart skript
RUN printf '%s\n' '#!/usr/bin/sh' \
  'adb start-server && \' \
  'emulator -avd android-30-x86_64 -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -nocache -no-snapshot-load -wipe-data' \
  > /entry.sh && chmod +x /entry.sh

ENTRYPOINT ["/usr/bin/sh"]
CMD ["/entry.sh"]
